### ISSUE TITLE
flatmap-stream dependecy missing

### ISSUE THREAD

**Issue by yardenporat** [rsuite/rsuite#1511]
### What version of rsuite are you using?
5.0.0-alpha.3

### What version of React are you using?
irrelevant, dev mode

### What browser are you using?
irrelevant, dev mode

### Describe the Bug
`npm i` doesn't work because of a missing package
![image](https://user-images.githubusercontent.com/56086371/108671342-f36a5980-74e8-11eb-904d-4c1e0efa2712.png)
![image](https://user-images.githubusercontent.com/56086371/108671432-1d238080-74e9-11eb-96f5-a9a99c3cea81.png)

### Expected Behavior
Should have all dependencies avaiable

### To Reproduce
1. clone repo
2. `npm i`

**Comment by simonguo** [comment]
I cannot reproduce your problem. Flatmap-stream is not used in the declared dependencies.
Please check the development environment, try to delete node_modules, then delete the cache and try again.
```
npm cache clean --force
```

**Comment by dekuofa1995** [comment]
> I cannot reproduce your problem. Flatmap-stream is not used in the declared dependencies.
> Please check the development environment, try to delete node_modules, then delete the cache and try again.
> 
> ```
> npm cache clean --force
> ```

尝试了还是失败
![image](https://user-images.githubusercontent.com/56107353/118066303-0ba79180-b3d1-11eb-9268-426114c9b3c8.png)

node：12.16.1
npm：7.12.1

**Comment by simonguo** [comment]
@dekuofa1995 我这边复现不了这个问题。
@hiyangguo 有遇到过这个问题，解决办法是修改 node 版本号到 v9，然后再重新升级。

你或者尝试一下以下命令
```
npm install --force
npm install --legacy-peer-deps
```

**Comment by dekuofa1995** [comment]
> @dekuofa1995 我这边复现不了这个问题。
> @hiyangguo 有遇到过这个问题，解决办法是修改 node 版本号到 v9，然后再重新升级。
> 
> 你或者尝试一下以下命令
> 
> ```
> npm install --force
> npm install --legacy-peer-deps
> ```

修改版本后成功安装
node: 10.24.1
npm: 6.14.12

注：v9 测试了几个版本，执行`npm run lint` 会报错
```
/rsuite/node_modules/eslint/bin/eslint.js:93
        } catch {
                ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
...
npm ERR! Failed at the rsuite@5.0.0-alpha.7 lint:ts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by hiyangguo** [comment]
> > @dekuofa1995 我这边复现不了这个问题。
> > @hiyangguo 有遇到过这个问题，解决办法是修改 node 版本号到 v9，然后再重新升级。
> > 你或者尝试一下以下命令
> > ```
> > npm install --force
> > npm install --legacy-peer-deps
> > ```
> 
> 修改版本后成功安装
> node: 10.24.1
> npm: 6.14.12
> 
> 注：v9 测试了几个版本，执行`npm run lint` 会报错
> 
> ```
> /rsuite/node_modules/eslint/bin/eslint.js:93
>         } catch {
>                 ^
> 
> SyntaxError: Unexpected token {
>     at new Script (vm.js:51:7)
> ...
> npm ERR! Failed at the rsuite@5.0.0-alpha.7 lint:ts script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> ```

修改 node 版本到 node@9 安装完成后，再切回原来的 node 版本就好了。甚至在高版本 node 安装 也不会报错了。

**Comment by hiyangguo** [comment]
> ### What version of rsuite are you using?
> 5.0.0-alpha.3
> 
> ### What version of React are you using?
> irrelevant, dev mode
> 
> ### What browser are you using?
> irrelevant, dev mode
> 
> ### Describe the Bug
> `npm i` doesn't work because of a missing package
> ![image](https://user-images.githubusercontent.com/56086371/108671342-f36a5980-74e8-11eb-904d-4c1e0efa2712.png)
> ![image](https://user-images.githubusercontent.com/56086371/108671432-1d238080-74e9-11eb-96f5-a9a99c3cea81.png)
> 
> ### Expected Behavior
> Should have all dependencies avaiable
> 
> ### To Reproduce
> 1. clone repo
> 2. `npm i`

@yardenporat 
1.  change node version to node@v9
2. `npm install`
3. change node version to any version you want use .
It's work fine , and you can execute `npm install` rather than having to switch node version.

**Comment by SevenOutman** [comment]
@yardenporat @dekuofa1995 If you're using npm 7, try removing `package-lock.json` before you do `npm install`. This works for me on my local machine.
