### ISSUE TITLE
Repository build fail on Windows

### ISSUE THREAD

**Issue by ivanvaccari** [rsuite/rsuite#3080]
### What version of rsuite are you using?

5.28.0

### What version of React are you using?

---

### What version of TypeScript are you using (if any)?

---

### What browser are you using?

---

### Describe the Bug

Just cloned the entire rsuite repository.
Without changing any file, the build launched with `npm run build` fails with various path errors and finally on testing some file presece.

Most suspicious point: some path generation is wrong, a concatenation of two absolute paths is performed.

Running on windows 10, node 16.16.0

Attached log:
```
PS C:\progetti\rsuite> npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> rsuite@5.28.0 build
> npm run build:gulp && npm run dist && npm run build:types

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> rsuite@5.28.0 build:gulp
> gulp build --gulpfile scripts/gulpfile.js

[18:41:21] Working directory changed to C:\progetti\rsuite\scripts
[18:41:23] Using gulpfile C:\progetti\rsuite\scripts\gulpfile.js
[18:41:23] Starting 'build'...
[18:41:23] Starting 'clean'...
[18:41:23] Finished 'clean' after 2.98 ms
[18:41:23] Starting 'buildCjs'...
[18:41:23] Starting 'buildEsm'...
[18:41:23] Starting 'buildLESS'...
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[18:41:29] Finished 'buildLESS' after 6.5 s
[18:41:29] Starting 'minifyCSS'...
[18:41:29] Starting 'buildRTLCSS'...
[18:41:34] Finished 'minifyCSS' after 4.32 s
[18:41:34] Finished 'buildRTLCSS' after 4.44 s
[18:41:47] Finished 'buildEsm' after 24 s
[18:41:47] Finished 'buildCjs' after 24 s
[18:41:47] Starting 'copyTypescriptDeclarationFiles'...
[18:41:47] Starting 'copyLessStylesheets'...
[18:41:47] Starting 'copyLessPlugins'...
[18:41:47] Starting 'copyDocs'...
[18:41:47] Starting 'createPkgFile'...
[18:41:47] Finished 'createPkgFile' after 53 ms
[18:41:47] Finished 'copyTypescriptDeclarationFiles' after 119 ms
[18:41:47] Finished 'copyLessPlugins' after 121 ms
[18:41:47] Finished 'copyDocs' after 121 ms
[18:41:47] Finished 'copyLessStylesheets' after 451 ms
[18:41:47] Starting 'buildDirectories'...
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Affix\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Animation\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\AutoComplete\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Avatar\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\@types\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Breadcrumb\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Badge\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Button\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\AvatarGroup\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\ButtonGroup\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\ButtonToolbar\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Calendar\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Carousel\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Cascader\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\CheckboxGroup\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Checkbox\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\CheckPicker\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\CheckTree\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\CheckTreePicker\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\CloseButton\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Col\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Content\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Container\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\CustomProvider\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\DatePicker\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Divider\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\DateRangePicker\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Disclosure\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\DOMHelper\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Drawer\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Dropdown\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\FlexboxGrid\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Footer\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Form\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\FormControl\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\FormControlLabel\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\FormErrorMessage\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\FormGroup\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\FormHelpText\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Grid\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Header\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\IconButton\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Input\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\InputGroup\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\InputNumber\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\InputPicker\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\List\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Loader\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\locales\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Menu\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Message\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\MaskedInput\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Modal\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\MultiCascader\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Nav\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Navbar\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Overlay\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Notification\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Pagination\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Panel\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\PanelGroup\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Picker\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Placeholder\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Plaintext\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Progress\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Radio\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Popover\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\RadioGroup\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\RangeSlider\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Rate\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Ripple\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Row\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\SafeAnchor\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Schema\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Sidebar\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\SelectPicker\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Sidenav\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Stack\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Slider\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Steps\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Table\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\styles\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Tag\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\TagInput\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\TagPicker\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\TagGroup\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Timeline\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\toaster\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Toggle\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Tree\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\TreePicker\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Uploader\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Tooltip\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\utils\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Whisper\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\C:\progetti\rsuite\src\Windowing\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\ar_EG\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\en_GB\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\de_DE\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\es_AR\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\fa_IR\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\es_ES\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\fi_FI\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\en_US\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\fr_FR\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\default\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\da_DK\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\hu_HU\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\index\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\kk_KZ\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\it_IT\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\ko_KR\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\nl_NL\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\sv_SE\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\ru_RU\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\zh_CN\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\zh_TW\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\pt_BR\package.json'
Error: ENOENT: no such file or directory, open 'C:\progetti\rsuite\lib\locales\C:\progetti\rsuite\src\locales\tr_TR\package.json'
[18:41:48] Finished 'buildDirectories' after 465 ms
[18:41:48] Finished 'build' after 25 s
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> rsuite@5.28.0 dist
> npm run dist:dev && npm run dist:pro

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> rsuite@5.28.0 dist:dev
> cross-env NODE_ENV=development  webpack --progress

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
asset rsuite.js 3.18 MiB [emitted] (name: rsuite) 1 related asset
runtime modules 1.31 KiB 6 modules
modules by path ./node_modules/ 1010 KiB
  modules by path ./node_modules/lodash/*.js 136 KiB 180 modules
  modules by path ./node_modules/date-fns/esm/ 374 KiB 52 modules
  modules by path ./node_modules/@rsuite/ 117 KiB 103 modules
  modules by path ./node_modules/rsuite-table/ 148 KiB 49 modules
  modules by path ./node_modules/dom-lib/esm/ 38.1 KiB 46 modules
  modules by path ./node_modules/@juggle/resize-observer/lib/ 21.4 KiB 24 modules
  modules by path ./node_modules/schema-typed/es/ 33.1 KiB 18 modules
  modules by path ./node_modules/@babel/runtime/ 20.7 KiB 16 modules
  modules by path ./node_modules/prop-types/ 27 KiB 5 modules
  modules by path ./node_modules/react-is/ 7.01 KiB 2 modules
modules by path ./src/ 1.38 MiB 384 modules
external {"root":"React","commonjs2":"react","commonjs":"react","amd":"react"} 42 bytes [built] [code generated]
external {"root":"ReactDOM","commonjs2":"react-dom","commonjs":"react-dom","amd":"react-dom"} 42 bytes [built] [code generated]
webpack 5.34.0 compiled successfully in 13269 ms
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> rsuite@5.28.0 dist:pro
> webpack --mode production --progress

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
asset rsuite.min.js 850 KiB [emitted] [minimized] [big] (name: rsuite) 2 related assets
orphan modules 424 KiB [orphan] 156 modules
runtime modules 1.31 KiB 6 modules
cacheable modules 2.23 MiB
  modules by path ./node_modules/ 971 KiB
    modules by path ./node_modules/lodash/*.js 136 KiB 180 modules
    modules by path ./node_modules/@rsuite/ 117 KiB 103 modules
    modules by path ./node_modules/date-fns/esm/ 374 KiB 19 modules
    modules by path ./node_modules/dom-lib/esm/ 38.1 KiB 34 modules
    modules by path ./node_modules/@babel/runtime/ 20.7 KiB 15 modules
    modules by path ./node_modules/prop-types/ 2.6 KiB 3 modules
    modules by path ./node_modules/rsuite-table/ 142 KiB 3 modules
  modules by path ./src/ 1.28 MiB 379 modules
external {"root":"React","commonjs2":"react","commonjs":"react","amd":"react"} 42 bytes [built] [code generated]
external {"root":"ReactDOM","commonjs2":"react-dom","commonjs":"react-dom","amd":"react-dom"} 42 bytes [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  rsuite.min.js (850 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  rsuite (850 KiB)
      rsuite.min.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.34.0 compiled with 3 warnings in 26441 ms
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> rsuite@5.28.0 build:types
> tsc --project tsconfig.build.json --emitDeclarationOnly --outDir lib/cjs && tsc --project tsconfig.build.json --emitDeclarationOnly --outDir lib/esm


> rsuite@5.28.0 postbuild
> mocha test/validateBuilds.js



  1) Ensure file existence
  ✔ Should enable Dark mode by default

  1 passing (9ms)
  1 failing

  1) Ensure file existence:

      AssertionError: File lib/C:\progetti\rsuite\src\@types/styles/index.less exists: expected false to be true
      + expected - actual

      -false
      +true

      at ensureFileExistence (test\validateBuilds.js:87:12)
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (test\validateBuilds.js:86:26)
      at processImmediate (node:internal/timers:466:21)

```

### Expected Behavior

Build complete successfully

### To Reproduce

git clone https://github.com/rsuite/rsuite.git
cd rsuite
npm install
npm run build.

**Comment by simonguo** [comment]
Hi @ivanvaccari  Looks like there is an error in getting the path here on Windows, you can try to fix it.
https://github.com/rsuite/rsuite/blob/f4025838b5971eb3f68057b69406a8f32b9a13d4/scripts/proxyDirectories.js#L16-L17

**Comment by ivanvaccari** [comment]
Found the problem.

https://github.com/rsuite/rsuite/blob/f4025838b5971eb3f68057b69406a8f32b9a13d4/scripts/proxyDirectories.js#L24

This lines supposedly extract the filename from the passed in path.
It works on linux where the regex match correctly the slashes, where it fails on windows which uses backslashes:

```
On linux: "/some/fake/dir.ts".replace(/[-_a-z0-9]*\//gi, '')
prints 'dir.ts'

On windows: "c:\\some\\fake\\dir.ts".replace(/[-_a-z0-9]*\//gi, '')
prints: 'c:\\some\\fake\\dir.ts'
```

This value is subsequentially joined to another path, which produces invalid paths on windows.
Replacing that line with 

```js
const pathname = path.basename(itemPath).replace('.ts', '');
```
Fixes the issue and builds on windows.

NOTE: didn't checked the result of the build, it just finish without errors and pass the final tests.
